### ISSUE TITLE
老哥，请问如何适配新版本

### ISSUE THREAD

**Issue by JackPan0519** [azwhikaru/fish_helper_config#3]
我研究了一下现有版本的配置文件，发现他们大多大同小异，然后a开头两位数字结尾的那几个文件里写着不同版本的不同数字（确实是一位数字），然后通过看commit发现7.6.70版本是老哥你前几天刚刚提交上去的，我想问一下，我该如何进行新版本的适配呢，谢谢了

**Comment by azwhikaru** [comment]
暂时不提供解密 Json 的方法，新版本没有大改的话，可以直接 Ctrl C+V 一份然后重命名成最新版的

**Comment by JackPan0519** [comment]
了解，感谢解答，还有个问题，配置文件目录下的[a40.json](https://github.com/azwhikaru/fish_helper_config/blob/main/release/adapter/a40.json)是起何作用哇，我看里面每个版本数组里的v对象对应的数字都不太一样

**Comment by JackPan0519** [comment]
> 暂时不提供解密 Json 的方法，新版本没有大改的话，可以直接 Ctrl C+V 一份然后重命名成最新版的

好的，谢谢老哥

**Comment by JackPan0519** [comment]
还有个小小的问题，配置文件目录下的[a40.json](https://github.com/azwhikaru/fish_helper_config/blob/main/release/adapter/a40.json)是起什么作用哇，我看每个版本对应的数组，v对象的数据（数字）都不太一样

**Comment by JackPan0519** [comment]
按照老哥前些日子的commit搞清楚文件作用了，再次感谢（
